---
title: "Hougang"
author: "Gareth"
date: "5/20/2020"
output: github_document
---

# Hougang

The first neighbourhood for fieldwork, it comprises of a traditionally Teochew Community in the North East. 

Some nuances of the neighbourhood:

- It has been popularised to be the 'opposition stronghold' though it holds multiple political constituencies. However, the term sticks and perpetuates a stereotype of the 'rebellious'  neighbourhood.

```{r message=FALSE,echo=FALSE, warning=FALSE}
library(tidyverse)
library(sf)
library(tmap)
library(tmaptools)
library(extrafont)
```

```{r message=FALSE,echo=FALSE,warning=FALSE}
hougangspaces1905<-read_csv(here::here('irpdata/Hougang19052020.csv'))
hougangspaces2205<-read_csv(here::here('irpdata/Hougang22052020.csv'))
hougangspaces0206<-read_csv(here::here('irpdata/Hougang02062020.csv'))
hougangspaces0506<-read_csv(here::here('irpdata/Hougang05062020.csv'))
hougangspaces0906<-read.csv(here::here('irpdata/Hougang09062020.csv'))
hougangspaces1006<-read.csv(here::here('irpdata/Hougang10062020.csv'))

planning_areas<-readRDS(here::here("irpdata/planning_areas.rds"))
Hougang<-planning_areas %>% 
  filter(PLN_AREA_N=="HOUGANG") %>% 
  filter(PLN_AREA_C=="HG") %>% 
  select(-REGION_N,-REGION_C)
```

```{r message=FALSE,echo=FALSE,warning=FALSE}
hougangspaces1905<-hougangspaces1905 %>% 
  st_as_sf(coords = c('lon', 'lat'))
hougangspaces2205<-hougangspaces2205 %>% 
  st_as_sf(coords = c('lon', 'lat'))
hougangspaces0206<-hougangspaces0206 %>% 
  st_as_sf(coords = c('lon', 'lat'))
hougangspaces0506<-hougangspaces0506 %>% 
  st_as_sf(coords = c('lon', 'lat'))
hougangspaces0906<-hougangspaces0906 %>% 
  st_as_sf(coords = c('lon', 'lat'))
hougangspaces1006<-hougangspaces1006 %>% 
  st_as_sf(coords = c('lon', 'lat'))

st_crs(hougangspaces1905)<-"+proj=longlat +datum=WGS84 +no_defs"
st_crs(hougangspaces2205)<-"+proj=longlat +datum=WGS84 +no_defs"
st_crs(hougangspaces0206)<-"+proj=longlat +datum=WGS84 +no_defs"
st_crs(hougangspaces0506)<-"+proj=longlat +datum=WGS84 +no_defs"
st_crs(hougangspaces0906)<-"+proj=longlat +datum=WGS84 +no_defs"
st_crs(hougangspaces1006)<-"+proj=longlat +datum=WGS84 +no_defs"
```

```{r message=FALSE,echo=FALSE,warning=FALSE}
tmap_mode("view")

tm_shape(Hougang)+
  tm_fill(col = "#E5ECC3",alpha = 0.2)+
  tm_borders(lty = "longdash")+
tm_shape(hougangspaces1905)+
  tm_symbols(size = 0.02, col= "Category", alpha=0.7)+
tm_shape(hougangspaces2205)+
  tm_symbols(size = 0.02, col= "Category", alpha=0.7,legend.col.show = FALSE)+
tm_shape(hougangspaces0206)+
  tm_symbols(size = 0.02, col= "Category", alpha=0.7,legend.col.show = FALSE)+
tm_shape(hougangspaces0506)+
  tm_symbols(size = 0.02, col= "Category", alpha=0.7,legend.col.show = FALSE)+
tm_shape(hougangspaces0906)+
  tm_symbols(size = 0.02, col= "Category", alpha=0.7,legend.col.show = FALSE)+
tm_shape(hougangspaces1006)+
  tm_symbols(size = 0.02, col= "Category", alpha=0.7,legend.col.show = FALSE)
```























