---
title: "Bedok"
author: "Gareth"
date: "6/25/2020"
output: html_document
---

# Bedok


```{r message=FALSE,echo=FALSE, warning=FALSE}
library(tidyverse)
library(sf)
library(tmap)
library(tmaptools)
library(extrafont)
library(janitor)
```


```{r message=FALSE,echo=FALSE,warning=FALSE}
bedokspaces1606<-read_csv(here::here('irpdata/Bedok16062020.csv'))
bedokspaces1906<-read_csv(here::here('irpdata/Bedok19062020.csv'))
bedokspaces2306<-read_csv(here::here('irpdata/Bedok23062020.csv'))
bedokspaces2406<-read_csv(here::here('irpdata/Bedok24062020.csv'))
bedokspaces2606<-read.csv(here::here('irpdata/Bedok26062020.csv'))
bedokspaces2706<-read.csv(here::here('irpdata/Bedok27062020.csv'))

bedokspaces1606<-clean_names(bedokspaces1606)
bedokspaces1906<-clean_names(bedokspaces1906)
bedokspaces2306<-clean_names(bedokspaces2306)
bedokspaces2406<-clean_names(bedokspaces2406)
bedokspaces2606<-clean_names(bedokspaces2606)
bedokspaces2706<-clean_names(bedokspaces2706)


planning_areas<-readRDS(here::here("irpdata/planning_areas.rds"))
Bedok<-planning_areas %>% 
  filter(PLN_AREA_N=="BEDOK") %>% 
  filter(PLN_AREA_C=="BD") %>% 
  select(-REGION_N,-REGION_C)
```


```{r message=FALSE,echo=FALSE,warning=FALSE}
bdpart1<-merge(bedokspaces1606,bedokspaces1906,all.x = TRUE,all.y = TRUE) 
bdpart1<-merge(bdpart1,bedokspaces2306,all.x = TRUE,all.y = TRUE)
bdpart1<-merge(bdpart1,bedokspaces2406,all.x = TRUE,all.y = TRUE)
bdpart1<-merge(bdpart1,bedokspaces2606,all.x = TRUE,all.y = TRUE)
bdpart1<-merge(bdpart1,bedokspaces2706,all.x = TRUE,all.y = TRUE)
```

```{r message=FALSE,echo=FALSE,warning=FALSE}
# bedokspaces1606<-bedokspaces1606 %>% 
#   st_as_sf(coords = c('lon', 'lat'))
# bedokspaces1906<-bedokspaces1906 %>% 
#   st_as_sf(coords = c('lon', 'lat'))
# bedokspaces2306<-bedokspaces2306 %>% 
#   st_as_sf(coords = c('lon', 'lat'))
# bedokspaces2406<-bedokspaces2406 %>% 
#   st_as_sf(coords = c('lon', 'lat'))
# bedokspaces2606<-bedokspaces2606 %>% 
#   st_as_sf(coords = c('lon', 'lat'))
# bedokspaces2706<-bedokspaces2706 %>% 
#   st_as_sf(coords = c('lon', 'lat'))
# 
# st_crs(bedokspaces1606)<-"+proj=longlat +datum=WGS84 +no_defs"
# st_crs(bedokspaces1906)<-"+proj=longlat +datum=WGS84 +no_defs"
# st_crs(bedokspaces2306)<-"+proj=longlat +datum=WGS84 +no_defs"
# st_crs(bedokspaces2406)<-"+proj=longlat +datum=WGS84 +no_defs"
# st_crs(bedokspaces2606)<-"+proj=longlat +datum=WGS84 +no_defs"
# st_crs(bedokspaces2706)<-"+proj=longlat +datum=WGS84 +no_defs"


bdpart1<-bdpart1 %>% 
   st_as_sf(coords = c('lon', 'lat'))

st_crs(bdpart1)<-"+proj=longlat +datum=WGS84 +no_defs"
```

```{r message=FALSE,echo=FALSE,warning=FALSE}
Bd_peoplegenerated<-bdpart1 %>% 
  filter(category=='People-generated')

Bd_peoplegenerated_VO<-Bd_peoplegenerated %>% 
  filter(!type_of_space=='Garden')
```


```{r message=FALSE,echo=FALSE,warning=FALSE}
tmap_mode("view")

tm_shape(Bedok)+
  tm_fill(col = "#E5ECC3",alpha = 0.2)+
  tm_borders(lty = "longdash")+
tm_shape(Bd_peoplegenerated_VO)+
  tm_symbols(size = 0.1, col= "type_of_space", alpha=0.7)
```

