--- 
title: "People-generated spaces and their developments in mature HDB estates"
author: "Gareth Conceicao 1004755"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
---
# Background

‘Building communities’ has been a consistent mandate within HDB when it comes to neighbourhood planning (HDB, 2017). HDB has created spaces for communities to exist through designation of resident corners at void decks, creation of community centres and small-scale food establishments such as void deck ‘coffeeshops’. In a country where most of the spaces and amenities have been designed through a central planning approach, community spaces in Singapore almost has a determinism design. Through the study of social interactions and behaviours, community spaces in Singapore have been curated in order to foster community development in HDB estates, albeit in the manner that is civically accepted by the state. In the midst of the state-provided spaces, people-generated spaces also exist, where residents have initiated their own spatial interventions. These interventions vary from additional furniture such as chairs and small coffee tables to build-in cabinets and fridges, creating an environment of cosiness that residents could enjoy.  People-generated spaces exhort a sense of community, with residents coming together and interacting in these spaces, along with their contributions to the space. These spaces play a role in neighbourhood planning as it creates an avenue where the community develops spaces for its’ specific needs (Checkoway, 1984). Yet, people-generated spaces remain relatively unknown in the mainstream knowledge of spaces in HDB estates in Singapore. This paper seeks to highlight the forms that people-generated spaces undertake as well as the themes that inspire or are impressed through the development of spaces in the context of community spaces in Singapore.


## People-generated Spaces

People-generated spaces in Singapore are hardly well documented, be it through academic publications or mainstream journalism. It shares similarities to community participatory planning, which is an increasingly used manifesto in  community space development in Singapore (URA, 2015; Nair, 2017). The development of the space is, by and large, by a community that shares an interest in the particular space and are not necessarily bound by geographic proximity (Jacobs, 1961). However, where it differs from community participatory planning is process of empowerment of the community into developing these spaces. Community participatory planning is often regarded as a collaboration between the state and community, with the former initiating the platform to empower the community to develop spaces. Be it during the conceptual stage or the feedback stage of the development of a project, the state essentially has empowered the community into making design decisions. Such projects often involve spaces that, as unique as they are intended to be, eventually serve a much larger demography than the community itself. Also, since it is state-driven, community participatory planning would still have to fall in line with urban planning technicalities such as amenity provision and accessibility requirements. People-generated spaces, on the other hand, is the innate empowerment of the community or residents to develop spaces of their own which fulfils the specific needs of that community. These spaces tend to border a line of accepted spatial interventions, whereby it does not cause concern for the overall community yet would probably only benefit those who have invested in it. Hence, people-generated spaces are more random and heterogeneous than projects that arise from community participatory planning.

People-generated spaces tend to resonate closely to Jacob’s definition of ‘street neighbourhood communities’, where the development of the space is not bound led through political power and yet it is able to form social spaces (Jacobs, 1961). As with the seemingly rebellious nature of people-generated spaces, they are subject to state approval once discovered. Especially if these spaces cause more harm to the neighbourhood community, people-generated spaces may cease to exist. However, they present a form of community space and resident empowerment that showcases how an unplanned space can support and create living communities. The uniqueness of the spatial interventions in people-generated spaces also speaks about the identity of the community in the space, just as much as the murals painted by community planning groups in HDB estates. It is important to see these spaces beyond notions of competition with existing community spaces, but how their development explains about community spaces in Singapore.
